//
//  Country.swift
//  SearchController
//
//  Created by Zac Workman on 29/01/2019.
//  Copyright © 2019 Kwip Limited. All rights reserved.
//

import Foundation

struct Country {
    let continent: String
    let title: String
    
    static func getAllCountries() -> [Country] {
        return [
            Country(continent:"América", title:"Argentina"),
            Country(continent:"América", title:"Brasil"),
            Country(continent:"América", title:"Chile"),
            Country(continent:"América", title:"Estados Unidos"),
            Country(continent:"América", title:"Paraguai"),
            Country(continent:"América", title:"México"),
            Country(continent:"América", title:"Canadá"),
            Country(continent:"América", title:"Antígua e Barbuda"),
            Country(continent:"América", title:"Bahamas"),
            Country(continent:"América", title:"Barbados"),
            Country(continent:"América", title:"Belize"),
            Country(continent:"América", title:"Costa Rica"),
            Country(continent:"América", title:"Cuba"),
            Country(continent:"América", title:"Dominica"),
            Country(continent:"América", title:"El Salvador"),
            Country(continent:"América", title:"Granada"),
            Country(continent:"América", title:"Guatemala"),
            Country(continent:"América", title:"Haiti"),
            Country(continent:"América", title:"Honduras"),
            Country(continent:"América", title:"Jamaica"),
            Country(continent:"América", title:"Nicarágua"),
            Country(continent:"América", title:"Panamá"),
            Country(continent:"América", title:"República Dominicana"),
            Country(continent:"América", title:"Santa Lúcia"),
            Country(continent:"América", title:"São Cristóvão e Névis "),
            Country(continent:"América", title:"São Vicente e Granadinas "),
            Country(continent:"América", title:"Trinidad e Tobago "),
            Country(continent:"América", title:"Bolívia"),
            Country(continent:"América", title:"Colômbia"),
            Country(continent:"América", title:"Equador"),
            Country(continent:"América", title:"Guiana"),
            Country(continent:"América", title:"Guiana Francesa"),
            Country(continent:"América", title:"Peru"),
            Country(continent:"América", title:"Suriname"),
            Country(continent:"América", title:"Uruguai"),
            Country(continent:"América", title:"Venezuela"),
            
            Country(continent:"Europa", title:"Alemanha"),
            Country(continent:"Europa", title:"Áustria"),
            Country(continent:"Europa", title:"Bélgica"),
            Country(continent:"Europa", title:"Bulgária"),
            Country(continent:"Europa", title:"Chipre"),
            Country(continent:"Europa", title:"Croácia"),
            Country(continent:"Europa", title:"Dinamarca"),
            Country(continent:"Europa", title:"Eslováquia"),
            Country(continent:"Europa", title:"Eslovênia"),
            Country(continent:"Europa", title:"Espanha"),
            Country(continent:"Europa", title:"Estônia"),
            Country(continent:"Europa", title:"Finlândia"),
            Country(continent:"Europa", title:"França"),
            Country(continent:"Europa", title:"Grécia"),
            Country(continent:"Europa", title:"Hungria"),
            Country(continent:"Europa", title:"Irlanda"),
            Country(continent:"Europa", title:"Itália"),
            Country(continent:"Europa", title:"Letônia"),
            Country(continent:"Europa", title:"Lituânia"),
            Country(continent:"Europa", title:"Luxemburogo"),
            Country(continent:"Europa", title:"Malta"),
            Country(continent:"Europa", title:"Países Baixos"),
            Country(continent:"Europa", title:"Polônia"),
            Country(continent:"Europa", title:"Reino Unido"),
            Country(continent:"Europa", title:"Romênia"),
            Country(continent:"Europa", title:"Suécia"),
            Country(continent:"Europa", title:"Tchéquia"),
            
            Country(continent:"África", title:"África do Sul"),
            Country(continent:"África", title:"Angola"),
            Country(continent:"África", title:"Argélia"),
            Country(continent:"África", title:"Burkina Faso"),
            Country(continent:"África", title:"Burundi"),
            Country(continent:"África", title:"Cabo Verde"),
            Country(continent:"África", title:"Camarões"),
            Country(continent:"África", title:"Chade"),
            Country(continent:"África", title:"Comores"),
            Country(continent:"África", title:"Costa do Marfim"),
            Country(continent:"África", title:"Djibouti"),
            Country(continent:"África", title:"Egito"),
            Country(continent:"África", title:"Eritreia"),
            Country(continent:"África", title:"Etiópia"),
            Country(continent:"África", title:"Gabão"),
            Country(continent:"África", title:"Gâmbia"),
            Country(continent:"África", title:"Gana"),
            Country(continent:"África", title:"Guiné"),
            Country(continent:"África", title:"Guiné-Bissau"),
            Country(continent:"África", title:"Guiné Equatorial"),
            Country(continent:"África", title:"Lesoto"),
            Country(continent:"África", title:"Libéria"),
            Country(continent:"África", title:"Líbia"),
            Country(continent:"África", title:"Madagáscar"),
            Country(continent:"África", title:"Malawi"),
            Country(continent:"África", title:"Mali"),
            Country(continent:"África", title:"Marrocos"),
            Country(continent:"África", title:"Maurícia"),
            Country(continent:"África", title:"Mauritânia"),
            Country(continent:"África", title:"Moçambique"),
            Country(continent:"África", title:"Namíbia"),
            Country(continent:"África", title:"Níger"),
            Country(continent:"África", title:"Nigéria"),
            Country(continent:"África", title:"Quénia"),
            Country(continent:"África", title:"República Centro-Africana"),
            Country(continent:"África", title:"República Democrática do Congo"),
            Country(continent:"África", title:"República do Congo"),
            Country(continent:"África", title:"Ruanda"),
            Country(continent:"África", title:"São Tomé e Príncipe"),
            Country(continent:"África", title:"Senegal"),
            Country(continent:"África", title:"Serra Leoa"),
            Country(continent:"África", title:"Seychelles"),
            Country(continent:"África", title:"Somália"),
            Country(continent:"África", title:"Suazilândia"),
            Country(continent:"África", title:"Sudão"),
            Country(continent:"África", title:"Sudão do Sul"),
            Country(continent:"África", title:"Tanzânia"),
            Country(continent:"África", title:"Togo"),
            Country(continent:"África", title:"Tunísia"),
            Country(continent:"África", title:"Uganda"),
            Country(continent:"África", title:"Zâmbia"),
            Country(continent:"África", title:"Zimbabwe"),
            Country(continent:"África", title:"Serra Leoa"),

            Country(continent:"Ásia", title:"Afeganistão"),
            Country(continent:"Ásia", title:"Arábia Saudita"),
            Country(continent:"Ásia", title:"Armênia"),
            Country(continent:"Ásia", title:"Azerbaijão"),
            Country(continent:"Ásia", title:"Bahrein"),
            Country(continent:"Ásia", title:"Bangladesh"),
            Country(continent:"Ásia", title:"Brunei"),
            Country(continent:"Ásia", title:"Butão"),
            Country(continent:"Ásia", title:"Camboja"),
            Country(continent:"Ásia", title:"Cazaquistão"),
            Country(continent:"Ásia", title:"Catar"),
            Country(continent:"Ásia", title:"China"),
            Country(continent:"Ásia", title:"Cingapura"),
            Country(continent:"Ásia", title:"Coréia do Norte"),
            Country(continent:"Ásia", title:"Coréia do Sul"),
            Country(continent:"Ásia", title:"Emirados Árabes"),
            Country(continent:"Ásia", title:"Filipinas"),
            Country(continent:"Ásia", title:"Lêmen"),
            Country(continent:"Ásia", title:"Irã"),
            Country(continent:"Ásia", title:"Iraque"),
            Country(continent:"Ásia", title:"Israel"),
            Country(continent:"Ásia", title:"Japão"),
            Country(continent:"Ásia", title:"Jordânia"),
            Country(continent:"Ásia", title:"Kuwait"),
            Country(continent:"Ásia", title:"Laos"),
            Country(continent:"Ásia", title:"Malásia"),
            Country(continent:"Ásia", title:"Maldivas"),
            Country(continent:"Ásia", title:"Mianmar"),
            Country(continent:"Ásia", title:"Mongólia"),
            Country(continent:"Ásia", title:"Nepal"),
            Country(continent:"Ásia", title:"Omã"),
            Country(continent:"Ásia", title:"Paquistão"),
            Country(continent:"Ásia", title:"Quirguistão"),
            Country(continent:"Ásia", title:"Síria"),
            Country(continent:"Ásia", title:"Rússia"),
            Country(continent:"Ásia", title:"Sri Lanka"),
            Country(continent:"Ásia", title:"Tajiquistão"),
            Country(continent:"Ásia", title:"Tailândia"),
            Country(continent:"Ásia", title:"Timor-Leste"),
            Country(continent:"Ásia", title:"Turcomenistão"),
            Country(continent:"Ásia", title:"Turquia"),
            Country(continent:"Ásia", title:"Uzbequistão"),
            Country(continent:"Ásia", title:"Vietnã"),

            Country(continent:"Oceania", title:"Austrália"),
            Country(continent:"Oceania", title:"Nova Zelândia"),
            Country(continent:"Oceania", title:"Fiji"),
            Country(continent:"Oceania", title:"Ilhas Marshall"),
            Country(continent:"Oceania", title:"Ilhas Salomão"),
            Country(continent:"Oceania", title:"Kiribati"),
            Country(continent:"Oceania", title:"Micronésia"),
            Country(continent:"Oceania", title:"Nauru"),
            Country(continent:"Oceania", title:"Palau"),
            Country(continent:"Oceania", title:"Papua Nova Guiné"),
            Country(continent:"Oceania", title:"Samoa"),
            Country(continent:"Oceania", title:"Tonga"),
            Country(continent:"Oceania", title:"Tuvalu"),
            Country(continent:"Oceania", title:"Vanuatu")
        ]
    }
}
